
spring:
  datasource:
    password: postgres
    url: "jdbc:postgresql://localhost:5432/camp"
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true